# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='box_size',
            field=models.CharField(choices=[('Small-box', 'Small'), ('Medium-box', 'Medium'), ('Large-box', 'Large')], max_length=100),
        ),
    ]
