# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160912_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
