# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 21:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160817_1157'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contenttype',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
