# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160817_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='item_row_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_subtitle',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='link'),
        ),
    ]
