# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160818_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
