# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
