# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160929_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
