# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160930_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hide_category',
            field=models.BooleanField(default=False, verbose_name='hide category'),
        ),
    ]
