# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_item_hide_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hide_category',
            field=models.CharField(choices=[('hide', 'hide')], default='', max_length=10),
        ),
    ]
