# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20161002_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hide_category',
            field=models.CharField(blank=True, choices=[('', ''), ('hide', 'hide')], max_length=10),
        ),
    ]
