# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20161002_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hide_category',
        ),
        migrations.AddField(
            model_name='category',
            name='hide_category',
            field=models.CharField(choices=[('', ''), ('hide', 'hide')], default='', max_length=10),
        ),
    ]
