# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20161002_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='hide_category',
        ),
    ]
