# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20161002_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hide',
            field=models.BooleanField(default='false'),
            preserve_default=False,
        ),
    ]
