# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_category_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hide',
        ),
    ]
