# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20161008_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
