# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_remove_item_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='excerpt',
            field=models.TextField(default='EXCERPT', max_length=200),
            preserve_default=False,
        ),
    ]
