# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_item_excerpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
