# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20161013_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(db_index=True),
        ),
    ]
