# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20161018_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(to='projects.Item'),
        ),
    ]
