# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20161018_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='projects',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='hi', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
