# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20161018_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
