# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20161019_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hero',
            field=models.ImageField(default='images/hero.png', upload_to='images/'),
        ),
    ]
